query GetOverdueInvoices($businessId: ID!, $page: Int!, $pageSize: Int!, $status: InvoiceStatus!) {
  business(id: $businessId) {
    id
    invoices(page: $page, pageSize: $pageSize, status: $status) {
      pageInfo {
        currentPage
        totalPages
        totalCount
      }
      edges {
        node {
          id
          createdAt
          modifiedAt
          pdfUrl
          viewUrl
          status
          invoiceNumber
          invoiceDate
          poNumber
          customer {
            id
            firstName
            name
            mobile
            email
          }
          dueDate
          amountDue {
            value
            currency {
              symbol
            }
          }
          taxTotal {
            value
            currency {
              symbol
            }
          }
          total {
            value
            currency {
              symbol
            }
          }
          lastSentAt
          lastSentVia
          lastViewedAt
        }
      }
    }
  }
}
